import { useState } from 'react';
import { ThumbsUp, Search, Hammer, Heart, UserPlus, Menu, ChevronLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useRouter } from 'next/navigation';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { motion } from 'framer-motion';

interface SidebarProps {
  activeTab: string;
  onTabChange: (tabId: string) => void;
}

export const tabs = [
  { id: 'overview', icon: ThumbsUp, label: 'Overview' },
  { id: 'searchability', icon: Search, label: 'Searchability' },
  { id: 'hardSkills', icon: Hammer, label: 'Hard Skills' },
  { id: 'softSkills', icon: Heart, label: 'Soft Skills' },
  { id: 'recruiterTips', icon: UserPlus, label: 'Recruiter Tips' },
];

export function Sidebar({ activeTab, onTabChange }: SidebarProps) {
  const [isOpen, setIsOpen] = useState(false);
  const router = useRouter();

  const handleBackClick = () => {
    router.push('/');
  };

  const handleTabChange = (id: string) => {
    onTabChange(id);
    setIsOpen(false);
  };

  const NavContent = () => (
    <div className="flex flex-col h-full bg-slate-950/50 backdrop-blur-xl border-r border-white/5 text-slate-100 p-4">
      <div className="flex items-center justify-between mb-8 px-2">
        <h2 className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 text-transparent bg-clip-text">Analysis Report</h2>
        <Button variant="ghost" size="icon" onClick={handleBackClick} className="text-slate-400 hover:text-white hover:bg-white/10">
          <ChevronLeft className="w-5 h-5" />
        </Button>
      </div>
      
      <div className="space-y-2 flex-1">
        {tabs.map((tab) => {
            const isActive = activeTab === tab.id;
            return (
                <button
                    key={tab.id}
                    onClick={() => handleTabChange(tab.id)}
                    className={`
                        w-full flex items-center space-x-3 px-4 py-3 rounded-xl transition-all duration-300 relative overflow-hidden group
                        ${isActive 
                            ? 'text-white font-semibold' 
                            : 'text-slate-400 hover:text-slate-200 hover:bg-white/5'}
                    `}
                >
                    {isActive && (
                        <motion.div 
                            layoutId="activeTab"
                            className="absolute inset-0 bg-gradient-to-r from-blue-600/20 to-cyan-500/20 border border-cyan-500/30 rounded-xl"
                            initial={false}
                            transition={{ type: "spring", stiffness: 500, damping: 30 }}
                        />
                    )}
                    <tab.icon className={`w-5 h-5 z-10 duration-300 ${isActive ? 'text-cyan-400' : 'text-slate-500 group-hover:text-slate-300'}`} />
                    <span className="z-10">{tab.label}</span>
                    {isActive && <div className="absolute right-3 w-1.5 h-1.5 rounded-full bg-cyan-400 shadow-[0_0_8px_rgba(6,182,212,0.8)] z-10" />}
                </button>
            );
        })}
      </div>
      
      <div className="mt-auto px-4 py-6 border-t border-white/5">
        <p className="text-xs text-slate-500 text-center">Generated by JobMatch AI</p>
      </div>
    </div>
  );

  return (
    <>
      {/* Desktop Sidebar */}
      <div className="hidden lg:block w-72 h-screen sticky top-0">
        <NavContent />
      </div>

      {/* Mobile Sidebar */}
      <div className="lg:hidden p-4 fixed top-0 w-full z-50 bg-slate-950/80 backdrop-blur-md border-b border-white/5 flex items-center justify-between">
         <span className="font-bold text-white">JobMatch Report</span>
        <Sheet open={isOpen} onOpenChange={setIsOpen}>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon" className="text-white">
              <Menu className="w-6 h-6" />
            </Button>
          </SheetTrigger>
          <SheetContent side="left" className="p-0 border-none w-72 bg-transparent text-white">
            <NavContent />
          </SheetContent>
        </Sheet>
      </div>
    </>
  );
}
